### ISSUE TITLE
Can't login since force update 0.57.4

### ISSUE THREAD

**Issue by pleilde** [Blossomforth/BlossomsPokemonGoManager#575]
Hello,

I can't login BPGM 1.7 since today with google token.
I have this error message:

[02:49:54]: D/GoogleUserCredentialProvider: Refreshed Token XxXfooXxX
[02:49:54]: D/RequestHandler: Authenticated with static token
[02:49:55]: Error: AsyncPokemonGoException
Unknown exception occurred. 
[02:50:09]: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
[02:50:09]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:55)
[02:50:09]:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:142)
[02:50:09]:     at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:229)
[02:50:09]:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:218)
[02:50:09]:     at me.corriekay.pokegoutil.utils.helpers.LoginHelper.login(LoginHelper.java:66)
[02:50:09]:     at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:338)
[02:50:09]:     at me.corriekay.pokegoutil.BlossomsPoGoManager.openOldGui(BlossomsPoGoManager.java:118)
[02:50:09]:     at me.corriekay.pokegoutil.BlossomsPoGoManager.start(BlossomsPoGoManager.java:70)
[02:50:09]:     at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:34)
[02:50:09]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[02:50:09]:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
[02:50:09]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
[02:50:09]:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
[02:50:09]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:44)
[02:50:09]:     ... 8 more
[02:50:09]: Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[02:50:09]:     at com.pokegoapi.main.ServerRequestEnvelope$1.get(ServerRequestEnvelope.java:86)
[02:50:09]:     at com.pokegoapi.main.ServerRequestEnvelope$1.get(ServerRequestEnvelope.java:70)
[02:50:09]:     at com.pokegoapi.main.ServerRequestEnvelope$1.get(ServerRequestEnvelope.java:50)
[02:50:09]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
[02:50:09]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
[02:50:09]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[02:50:09]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[02:50:09]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[02:50:09]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[02:50:09]:     at rx.Observable.subscribe(Observable.java:9957)
[02:50:09]:     at rx.Observable.subscribe(Observable.java:9924)
[02:50:09]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
[02:50:09]:     ... 10 more
[02:50:09]: Caused by: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[02:50:09]:     at com.pokegoapi.main.RequestHandler.sendInternal(RequestHandler.java:269)
[02:50:09]:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:384)
[02:50:09]:     at java.lang.Thread.run(Thread.java:745)

**Comment by Cirunz** [comment]
aaaand +1
Either using google with Oauth token or PTC

**Comment by jonmabbutt** [comment]
Same for me with Google . Has anyone had the warning exclusively through using this? ie not using any other botting/spoofing/IV checking apps that login with your account?

**Comment by netgh0st** [comment]
I have been using Blossom and recently IvGo, haven't had the warning. I was using them quite rarely though.

**Comment by notoriouspeb** [comment]
Used often. No warning FWIW

**Comment by schagnon** [comment]
My warning came 48 hours later and it's about every other time I login.
No spoofing or any other misgivings.

@Wolfsblvt any chance you can approach Niantic with what issue they have
with Blossom and then shutoff that functionality?    It would be great to
get it 'allowed'




-Steven Chagnon
Lead Admin for
Tennis League Network, LLC:
Servicing 35 Tennis
Communities Nationwide.
It's not always about the ace.

**Comment by PolyglotOpenstreetmap** [comment]
There is zero chance Niantic will somehow allow our 'Manager'. As far as they are concernced you're getting an unfair advantage against the other players and you're using software they don't have control over and which can just as well be used to create Bots.

**Comment by FernandoTBarros** [comment]
Duplicated from #576 
Only login with hashkey since 0.57.4 force update
