### ISSUE TITLE
Impossible to connect with google account (no proxy/vpn/firewall)

### ISSUE THREAD

**Issue by GuillaumeCisco** [Blossomforth/BlossomsPokemonGoManager#579]
Impossible to connect with my google account, I disabled 2 step verification, activated less secured application authentication.

console.log file give me an error like:
```
[14:07:29]: Caused by: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[14:07:29]: 	at com.pokegoapi.main.RequestHandler.sendInternal(RequestHandler.java:269)
[14:07:29]: 	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:384)
[14:07:29]: 	at java.lang.Thread.run(Unknown Source)
```

0.1.6 was working 2 weeks agos.
Now, 0.1.6 and 0.1.7 does not work :/

**Comment by FernandoTBarros** [comment]
The free API was discontinued by Niantic.
You can only login using a hashkey and the hotfix version available in Discord channel.

**Comment by Cecelo** [comment]
Where are the link to Discord channel

**Comment by marcelohenrique** [comment]
On github project description. https://discord.gg/E9v8RRb

**Comment by r4dpere** [comment]
Guys where can i buy the hash key? Thanks.
